# Generated by Django 4.2.18 on 2025-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="User profile avatar",
                null=True,
                upload_to="users_images",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, help_text="User phone number", max_length=10, null=True
            ),
        ),
    ]
