services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: motoapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: motoapp
    ports:
      - "5432:5432"
  
  app:
    build:
      context: .
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    restart: on-failure
    environment:
      DEBUG: "False"
      DB_NAME: motoapp
      DB_USER: motoapp
      DB_PASSWORD: 1234
      DB_HOST: "postgres"
      DB_PORT: 5432

# nginx:
#   image: nginx:latest
#   volume:

