# Generated by Django 4.2.18 on 2025-05-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
        ("carts", "0001_initial"),
        ("catalog", "0006_products_product_search_vector_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Categories",
            new_name="Category",
        ),
        migrations.RenameModel(
            old_name="Products",
            new_name="Product",
        ),
    ]
