# Generated by Django 4.2.18 on 2025-05-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_options_alter_order_created_timestamp_and_more"),
        ("carts", "0001_initial"),
        ("catalog", "0007_rename_categories_category_rename_products_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Categories",
        ),
        migrations.RenameModel(
            old_name="Product",
            new_name="Products",
        ),
    ]
