# Generated by Django 4.2.18 on 2025-04-17 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0005_categories_description_categories_image"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("id",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "ordering": ("id",),
                "verbose_name": "Sold product",
                "verbose_name_plural": "Sold products",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания заказа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Оплачено"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_on_get",
            field=models.BooleanField(
                default=False, verbose_name="Оплата при получении"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="order",
            name="requires_delivery",
            field=models.BooleanField(default=False, verbose_name="Требуется доставка"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="Order in progress", max_length=50, verbose_name="Статус заказа"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Цена"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='catalog.Products',
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество"),
        ),
    ]
