# Generated by Django 4.2.18 on 2025-05-09 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0007_rename_categories_category_rename_products_product"),
        ("orders", "0002_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("id",),
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="created_timestamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Order creation date"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Delivery address"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Paid"),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_on_get",
            field=models.BooleanField(default=False, verbose_name="Cash on delivery"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Phone number"),
        ),
        migrations.AlterField(
            model_name="order",
            name="requires_delivery",
            field=models.BooleanField(default=False, verbose_name="Delivery required"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="Order in progress", max_length=50, verbose_name="Order status"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="created_timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date of Sale"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=7, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to='catalog.Product',
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
    ]
